<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-IT7687" failures="1" tests="2" name="demoTest" time="5.955" errors="0" timestamp="2023-02-04T19:29:44 IST">
  <testcase classname="base.FirstTestClass" name="checkFailure" time="0.025">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at base.FirstTestClass.checkFailure(FirstTestClass.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- checkFailure -->
  <testcase classname="base.FirstTestClass" name="checkLogin" time="5.856"/>
</testsuite> <!-- demoTest -->
